# Generated by Django 4.2.1 on 2023-05-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_delete_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
